### ISSUE TITLE
What kind of deep reinforcement learning method does this algorithm belong to

### ISSUE THREAD

**Issue by persomeman** [revenol/DROO#3]
What kind of deep reinforcement learning method does this algorithm belong to

**Comment by revenol** [comment]
The DROO algorithm works in an actor-critic way, Somehow, it is similar to semi-supervised learning without pre-generated training data.

**Comment by pingzhou3** [comment]
hi, I'm confused with the bisection algorithm applied in the optimization python file. Can you give a detailed explanation or derivation process? It is very important to me. Thanks a lot!

**Comment by persomeman** [comment]
Sorry, I can't provide more help, I suggest you directly consult the author.




---Original---

**Comment by hiranaeem** [comment]
Hi. Sir Is this algorithm DROO will improve its mobility issues in future? Sent from Mail for Windows 10 From: Liang HUANGSent: Tuesday, August 10, 2021 5:56 AMTo: revenol/DROOCc: SubscribedSubject: Re: [revenol/DROO] What kind of deep reinforcement learning method does this algorithm belong to (#3) Closed #3.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by revenol** [comment]
Hi,
Sorry but what do you mean by the mobility issues? DROO is supposed to support networks with mobility.


Best Regards,
REVENOL

**Comment by hiranaeem** [comment]
Thanks for your reply. Sir I was asking about vehicular networks .... Does
this algorithm DROO will support vehicular networks or not?
